name: NHS Digital - CIS URS Service
description: |
  Stands up CIS URS Service, requires CIS-Externals stack for access to PKI, Directory and Database.
version: 0.1
category: NHS-Digital
maintainer: NHS-Digital